version: "3.9"
services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"
    command: [ "yarn", "run", "start:debug" ]
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: inarcv_postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
